/***EEG DEFINITIONS ***/
#define NOT_FOUND       -1 
#define N_ELECT         256
#define MAX_EPOCH       64
#define MAXEPOCH        128
#define MAX_PNTS        512
#define TIME            0
#define FREQ            1
#define EXTERN          0
#define INTERN          1
#define PPORT           2
#define LPP             3
#define COM1            5             
#define COM2            6
#define LPT1            7
#define LPT2            8
#define NOTRIG          9
#define COM             10
#define RISE            1
#define FALL            2
#define RATE            15
#define MAXARRAY        512
#define AVERAGED        0
#define AVGD            1
#define EEGF            0
#define EEG             1
#define BOTH            2
#define CONT            3
#define NOSTORE         4
#define MTF             5
#define FSP             6
#define CSA             7
#define GROUP           2
#define COMPARISON      3
#define RELATIVE        4
#define GROUPCOMP       5
#define MEANFREQ        6
#define UP              0
#define DWN             1
#define RATIO           1
#define DIFF            2
#define TSCORE          3
#define ZSCORE          4
#define AUTOCORR        5
#define ADD             6
#define TOP             0
#define DMA40           0
#define DMA100          1
#define AD              2
#define DCMES           3
#define SYNAMPS         4
// events:
#define SAVESTART       0xf
#define SAVESTOP        0xe
#define ACCEPT          0xd
#define REJECT          0xc
#define DCCORRECTION    0xb

// for continuous type 0:
#define ACCEPT0         -3
#define REJECT0         -4

#define POS             0
#define NEG             1
